version: '3.8'

services:
  # PHP-FPM Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mims_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mims_network
    depends_on:
      - db
      - redis

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: mims_webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/nginx/ssl/
    networks:
      - mims_network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mims_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mims
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: mims_user
      MYSQL_PASSWORD: mims_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - mims_network
    command: --default-authentication-plugin=mysql_native_password

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: mims_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mims_network

  # phpMyAdmin (Development only)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mims_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    networks:
      - mims_network
    depends_on:
      - db
    profiles:
      - dev

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  mims_network:
    driver: bridge
